### ISSUE TITLE
Error downloading LASC PDF

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1027]
Not sure what's going on here. Let me know if I can help:

```
task-server_celery_prefork_bulk.3.wu4kr71rmzsw@debian    | [2019-10-16 13:27:44,520: ERROR/ForkPoolWorker-6] Task cl.lasc.tasks.download_pdf[409cfe87-33cf-4862-b391-bf39a5af4291] raised unexpected: MultipleObjectsReturned('get() returned more than one DocumentImage -- it returned 2!',)
task-server_celery_prefork_bulk.3.wu4kr71rmzsw@debian    | Traceback (most recent call last):
task-server_celery_prefork_bulk.3.wu4kr71rmzsw@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 385, in trace_task
task-server_celery_prefork_bulk.3.wu4kr71rmzsw@debian    |     R = retval = fun(*args, **kwargs)
task-server_celery_prefork_bulk.3.wu4kr71rmzsw@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
task-server_celery_prefork_bulk.3.wu4kr71rmzsw@debian    |     return self.run(*args, **kwargs)
task-server_celery_prefork_bulk.3.wu4kr71rmzsw@debian    |   File "/opt/celery/cl/lasc/tasks.py", line 98, in download_pdf
task-server_celery_prefork_bulk.3.wu4kr71rmzsw@debian    |     doc = DocumentImage.objects.get(doc_id=q_pdf.document_id)
task-server_celery_prefork_bulk.3.wu4kr71rmzsw@debian    |   File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
task-server_celery_prefork_bulk.3.wu4kr71rmzsw@debian    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
task-server_celery_prefork_bulk.3.wu4kr71rmzsw@debian    |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 384, in get
task-server_celery_prefork_bulk.3.wu4kr71rmzsw@debian    |     (self.model._meta.object_name, num)
task-server_celery_prefork_bulk.3.wu4kr71rmzsw@debian    | Exception: get() returned more than one DocumentImage -- it returned 2!
task-server_celery_prefork_bulk.1.5tm2ss569lm1@debian    | [2019-10-16 13:24:47,304: INFO/MainProcess] Received task: cl.lasc.tasks.download_pdf[315550ac-7345-451d-b245-1535f0c00f81]  ETA:[2019-10-16 20:25:47.298848+00:00] 
task-server_celery_prefork_bulk.1.5tm2ss569lm1@debian    | [2019-10-16 13:25:50,350: ERROR/ForkPoolWorker-7] Task cl.lasc.tasks.download_pdf[315550ac-7345-451d-b245-1535f0c00f81] raised unexpected: MultipleObjectsReturned('get() returned more than one DocumentImage -- it returned 2!',)
task-server_celery_prefork_bulk.1.5tm2ss569lm1@debian    | Traceback (most recent call last):
task-server_celery_prefork_bulk.1.5tm2ss569lm1@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 385, in trace_task
task-server_celery_prefork_bulk.1.5tm2ss569lm1@debian    |     R = retval = fun(*args, **kwargs)
task-server_celery_prefork_bulk.1.5tm2ss569lm1@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
task-server_celery_prefork_bulk.1.5tm2ss569lm1@debian    |     return self.run(*args, **kwargs)
task-server_celery_prefork_bulk.1.5tm2ss569lm1@debian    |   File "/opt/celery/cl/lasc/tasks.py", line 98, in download_pdf
task-server_celery_prefork_bulk.1.5tm2ss569lm1@debian    |     doc = DocumentImage.objects.get(doc_id=q_pdf.document_id)
task-server_celery_prefork_bulk.1.5tm2ss569lm1@debian    |   File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
task-server_celery_prefork_bulk.1.5tm2ss569lm1@debian    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
task-server_celery_prefork_bulk.1.5tm2ss569lm1@debian    |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 384, in get
task-server_celery_prefork_bulk.1.5tm2ss569lm1@debian    |     (self.model._meta.object_name, num)
task-server_celery_prefork_bulk.1.5tm2ss569lm1@debian    | Exception: get() returned more than one DocumentImage -- it returned 2!
```

Just got that back from Celery.

**Comment by flooie** [comment]
Do you have any more of the log.  Any chance you have the doc_id it queried?
