### ISSUE TITLE
Partial dates not supported by Harvard importer

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1142]
I think we knew we'd run into this eventually. We ran into it before too. It happens in old cases pretty frequently that we don't actually know — it's lost to history — the date a decision was promulgated. Instead we know the month or that it was in the Fall session or whatever. 

Anyway, now we're hitting it while importing the Board of Tax Appeals docs:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/www/courtlistener/cl/corpus_importer/management/commands/harvard_opinions.py", line 410, in handle
    parse_harvard_opinions(reporter, volume, make_searchable)
  File "/var/www/courtlistener/cl/corpus_importer/management/commands/harvard_opinions.py", line 318, in parse_harvard_opinions
    filepath_json_harvard=file_path,
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/var/www/courtlistener/cl/search/models.py", line 2229, in save
    super(OpinionCluster, self).save(*args, **kwargs)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/query.py", line 1079, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1111, in execute_sql
    for sql, params in self.as_sql():
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1064, in as_sql
    for obj in self.query.objs
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1003, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 770, in get_db_prep_save
    prepared=False)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1301, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1296, in get_prep_value
    return self.to_python(value)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1271, in to_python
    params={'value': value},
django.core.exceptions.ValidationError: [u"'1934-01' value has an invalid date format. It must be in YYYY-MM-DD format."]
```

The specific case with the issue is: 

API: https://api.case.law/v1/cases/6075903/
HTML: https://cite.case.law/bta/29/702/

The API shows that we only have the year. The HTML shows that the Harvard people are comfortable displaying such a date as `Jan 1, 1934`.

We have code for this if we grep for `date_is_approximate`. I think.

**Comment by mlissner** [comment]
Filed a bug with capstone too: https://github.com/harvard-lil/capstone/issues/1300

**Comment by flooie** [comment]
Added support for YYYY.
