### ISSUE TITLE
Queries with tax court abbreviations in them can fail

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1160]
See, for example, https://www.courtlistener.com/?q=2019+T.C.+Summary+Opinion+19

Pulling up the error email shows the following exception info (sorry the stacktrace is a pain to get from the email):

```
ValueError at /
need more than 1 value to unpack
```

It then points at line 398 of find_citations.py, which has (drum roll):

```if neutral_tc_reporter:
        volume, page = (
            words[reporter_index + 1]
            .encode("utf-8")
            .replace("–", "-")
            .split("-")
        )```

This will need a little tweak to make it work properly.

**Comment by flooie** [comment]
We built a method to handle atypical tax court cases.

For example: T.C. Memo 2019-12.  This gets saved and stored as 
2019 T.C. Memo 12 in our database.  But running 2019 T.C. Memo 12
into our system recognizes 2019 T.C. Memo 12 as a atypical tax case 
even though it is now in a typical format.  Processing a typical
format in the atypical (specialized) way caused the crash.  

The fix is moving one step back and adding a ```reporter_index == 0``` 
```
    neutral_tc_reporter = is_neutral_tc_reporter(reporter)
    if neutral_tc_reporter and reporter_index == 0:  <--- here
        volume, page = (
            words[reporter_index + 1]
            .encode("utf-8")
            .replace("–", "-")
            .split("-")
        )

```

Otherwise the new format should be treated like a typical case and parsed normally.

**Comment by mlissner** [comment]
Actually just saw this in our citation parser as well. I don't know the case, but I have this traceback:

```
1854abecb1f9] raised unexpected: ValueError('need more than 1 value to unpack',)
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    | Traceback (most recent call last):
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 385, in trace_task
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |     R = retval = fun(*args, **kwargs)
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |     return self.run(*args, **kwargs)
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |   File "/opt/celery/cl/citations/tasks.py", line 103, in find_citations_for_opinion_by_pks
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |     citations = get_document_citations(opinion)
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/local.py", line 191, in __call__
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |     return self._get_current_object()(*a, **kw)
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 649, in __protected_call__
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |     return orig(self, *args, **kwargs)
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/task.py", line 394, in __call__
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |     return self.run(*args, **kwargs)
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |   File "/opt/celery/cl/citations/tasks.py", line 60, in get_document_citations
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |     citations = find_citations.get_citations(opinion.html_lawbox)
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |   File "/opt/celery/cl/citations/find_citations.py", line 578, in get_citations
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |     citation = extract_full_citation(words, i)
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |   File "/opt/celery/cl/citations/find_citations.py", line 279, in extract_full_citation
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |     .split("-")
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    | ValueError: need more than 1 value to unpack
```

**Comment by flooie** [comment]
We updated the method for extracting citations into juriscraper that we could/should use to fix this bug.  This lets us remove unnecessary code from CL as well.

**Comment by flooie** [comment]
This no longer errors - so I assume this was fixed.
