### ISSUE TITLE
Fix crashes in depth of treatment citation finder

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1171]
Just going to file these here as I see them:

```
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    | [2020-02-06 15:32:06,713: ERROR/ForkPoolWorker-6] Task cl.citations.tasks.find_citations_for_opinion_by_pks[04cd5ad6-d218-4713-b0ac-6b24f4c004ba] raised unexpected: IndexError('list index out of range',)
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    | Traceback (most recent call last):
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 385, in trace_task
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    |     R = retval = fun(*args, **kwargs)
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    |     return self.run(*args, **kwargs)
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    |   File "/opt/celery/cl/citations/tasks.py", line 103, in find_citations_for_opinion_by_pks
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    |     citations = get_document_citations(opinion)
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/local.py", line 191, in __call__
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    |     return self._get_current_object()(*a, **kw)
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 649, in __protected_call__
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    |     return orig(self, *args, **kwargs)
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/task.py", line 394, in __call__
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    |     return self.run(*args, **kwargs)
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    |   File "/opt/celery/cl/citations/tasks.py", line 62, in get_document_citations
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    |     citations = find_citations.get_citations(opinion.html)
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    |   File "/opt/celery/cl/citations/find_citations.py", line 579, in get_citations
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    |     citation = extract_shortform_citation(words, i)
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    |   File "/opt/celery/cl/citations/find_citations.py", line 333, in extract_shortform_citation
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    |     page = parse_page(words[reporter_index + 3])
task-server_celery_prefork.3.gpwz5n1fu5gd@debian    | IndexError: list index out of range
```

**Comment by mlissner** [comment]
Another: 

```
task-server_celery_prefork.5.r1zjkn59zvlm@debian    | [2020-02-06 15:31:35,419: ERROR/ForkPoolWorker-4] Task cl.citations.tasks.find_citations_for_opinion_by_pks[a68c11c5-5292-4aaa-aacb-01d67a8ed05d] raised unexpected: IndexError('list index out of range',)
task-server_celery_prefork.5.r1zjkn59zvlm@debian    | Traceback (most recent call last):
task-server_celery_prefork.5.r1zjkn59zvlm@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 385, in trace_task
task-server_celery_prefork.5.r1zjkn59zvlm@debian    |     R = retval = fun(*args, **kwargs)
task-server_celery_prefork.5.r1zjkn59zvlm@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
task-server_celery_prefork.5.r1zjkn59zvlm@debian    |     return self.run(*args, **kwargs)
task-server_celery_prefork.5.r1zjkn59zvlm@debian    |   File "/opt/celery/cl/citations/tasks.py", line 103, in find_citations_for_opinion_by_pks
task-server_celery_prefork.5.r1zjkn59zvlm@debian    |     citations = get_document_citations(opinion)
task-server_celery_prefork.5.r1zjkn59zvlm@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/local.py", line 191, in __call__
task-server_celery_prefork.5.r1zjkn59zvlm@debian    |     return self._get_current_object()(*a, **kw)
task-server_celery_prefork.5.r1zjkn59zvlm@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 649, in __protected_call__
task-server_celery_prefork.5.r1zjkn59zvlm@debian    |     return orig(self, *args, **kwargs)
task-server_celery_prefork.5.r1zjkn59zvlm@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/task.py", line 394, in __call__
task-server_celery_prefork.5.r1zjkn59zvlm@debian    |     return self.run(*args, **kwargs)
task-server_celery_prefork.5.r1zjkn59zvlm@debian    |   File "/opt/celery/cl/citations/tasks.py", line 65, in get_document_citations
task-server_celery_prefork.5.r1zjkn59zvlm@debian    |     opinion.plain_text, html=False
task-server_celery_prefork.5.r1zjkn59zvlm@debian    |   File "/opt/celery/cl/citations/find_citations.py", line 600, in get_citations
task-server_celery_prefork.5.r1zjkn59zvlm@debian    |     citation = extract_supra_citation(words, i)
task-server_celery_prefork.5.r1zjkn59zvlm@debian    |   File "/opt/celery/cl/citations/find_citations.py", line 375, in extract_supra_citation
task-server_celery_prefork.5.r1zjkn59zvlm@debian    |     page = parse_page(words[supra_index + 2])
task-server_celery_prefork.5.r1zjkn59zvlm@debian    | IndexError: list index out of range
```

**Comment by mlissner** [comment]
```
task-server_celery_prefork.1.3ghp52nsn3wv@debian    | [2020-02-06 15:32:39,368: ERROR/ForkPoolWorker-4] Task cl.citations.tasks.find_citations_for_opinion_by_pks[c9c38b5c-315f-42f9-afdb-988a94621893] raised unexpected: UnicodeDecodeError('ascii', '924e\xe2\x80\x99s', 4, 5, 'ordinal not in range(128)')
task-server_celery_prefork.1.3ghp52nsn3wv@debian    | Traceback (most recent call last):
task-server_celery_prefork.1.3ghp52nsn3wv@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 385, in trace_task
task-server_celery_prefork.1.3ghp52nsn3wv@debian    |     R = retval = fun(*args, **kwargs)
task-server_celery_prefork.1.3ghp52nsn3wv@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
task-server_celery_prefork.1.3ghp52nsn3wv@debian    |     return self.run(*args, **kwargs)
task-server_celery_prefork.1.3ghp52nsn3wv@debian    |   File "/opt/celery/cl/citations/tasks.py", line 130, in find_citations_for_opinion_by_pks
task-server_celery_prefork.1.3ghp52nsn3wv@debian    |     opinion.html_with_citations = create_cited_html(opinion, citations)
task-server_celery_prefork.1.3ghp52nsn3wv@debian    |   File "/opt/celery/cl/citations/tasks.py", line 84, in create_cited_html
task-server_celery_prefork.1.3ghp52nsn3wv@debian    |     repl = u'</pre>%s<pre class="inline">' % citation.as_html()
task-server_celery_prefork.1.3ghp52nsn3wv@debian    |   File "/opt/celery/cl/citations/models.py", line 237, in as_html
task-server_celery_prefork.1.3ghp52nsn3wv@debian    |     inner_html = inner_html % (self.volume, self.reporter, self.page)
task-server_celery_prefork.1.3ghp52nsn3wv@debian    | UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4: ordinal not in range(128)
```

**Comment by mlissner** [comment]
@mattdahl should this be fixed now in your estimation? If so, I'll do a deploy and see what the logs look like.

**Comment by mattdahl** [comment]
Yes, hopefully! Feel free to deploy and let me know
