### ISSUE TITLE
Encoding error in latest citation parsing

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1181]
Just got this error while parsing citations:

```
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    | [2020-02-11 15:51:04,923: ERROR/ForkPoolWorker-5] Task cl.citations.tasks.find_citations_for_opinion_by_pks[13e581bf-0899-43d5-b561-e27b228b8815] raised unexpected: UnicodeDecodeError('ascii', '160.\xc2\x97it', 4, 5, 'ordinal not in range(128)')
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    | Traceback (most recent call last):
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 385, in trace_task
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |     R = retval = fun(*args, **kwargs)
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |     return self.run(*args, **kwargs)
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |   File "/opt/celery/cl/citations/tasks.py", line 109, in find_citations_for_opinion_by_pks
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |     opinion, citations
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |   File "/opt/celery/cl/citations/match_citations.py", line 239, in get_citation_matches
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |     matches = match_citation(citation, citing_doc=citing_opinion)
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |   File "/opt/celery/cl/citations/match_citations.py", line 138, in match_citation
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |     main_params["fq"].append('citation:("%s")' % citation.base_citation())
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |   File "/opt/celery/cl/citations/models.py", line 86, in base_citation
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    |     return u"%d %s %s" % (self.volume, self.reporter, self.page)
task-server_celery_prefork_bulk.4.ghyo3d23g44b@debian    | UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 4: ordinal not in range(128)
```

The code it is failing on is:

```
    def base_citation(self):
        return u"%d %s %s" % (self.volume, self.reporter, self.page)
```

Which looks like old code, so I'm curious what's going on there, but if I understand this correctly, self.volume, self.reporter, and self.page are all strings that are getting decoded using the ascii codec, so that's the issue. 

I guess then, my question is why these aren't unicode already. In theory we should really only be dealing with unicode once we pull from the DB unless we encode to strings at some point.

**Comment by mlissner** [comment]
One more note. I guess the simple fix is to do `self.volume.decode('utf-8')`, but that sort of elides the bigger issue and makes us play whak-a-mole.

**Comment by mlissner** [comment]
We ran several million items through the citator and I'm confident saying this is fixed.
