### ISSUE TITLE
Bad regex in citation finder

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1182]
Another little error: 

```
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    | [2020-02-11 16:28:31,127: ERROR/ForkPoolWorker-5] Task cl.citations.tasks.find_citations_for_opinion_by_pks[d0c1c4f4-32d2-4c12-ac58-4fc45d6a3050] raised unexpected: error('unbalanced parenthesis',)
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    | Traceback (most recent call last):
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 385, in trace_task
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |     R = retval = fun(*args, **kwargs)
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |     return self.run(*args, **kwargs)
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |   File "/opt/celery/cl/citations/tasks.py", line 130, in find_citations_for_opinion_by_pks
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |     opinion.html_with_citations = create_cited_html(opinion, citations)
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |   File "/opt/celery/cl/citations/tasks.py", line 78, in create_cited_html
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |     citation.as_regex(), citation.as_html(), new_html
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |   File "/usr/local/lib/python2.7/re.py", line 155, in sub
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |     return _compile(pattern, flags).sub(repl, string, count)
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |   File "/usr/local/lib/python2.7/re.py", line 251, in _compile
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |     raise error, v # invalid expression
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    | error: unbalanced parenthesis
```

**Comment by mlissner** [comment]
And another, similar error:

```
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    | [2020-02-11 16:18:57,987: ERROR/ForkPoolWorker-3] Task cl.citations.tasks.find_citations_for_opinion_by_pks[4dea6d15-e1ac-4492-bcf3-1fc8aec6c022] raised unexpected: error('unmatched group',)
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    | Traceback (most recent call last):
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 385, in trace_task
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |     R = retval = fun(*args, **kwargs)
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |     return self.run(*args, **kwargs)
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |   File "/opt/celery/cl/citations/tasks.py", line 130, in find_citations_for_opinion_by_pks
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |     opinion.html_with_citations = create_cited_html(opinion, citations)
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |   File "/opt/celery/cl/citations/tasks.py", line 78, in create_cited_html
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |     citation.as_regex(), citation.as_html(), new_html
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |   File "/usr/local/lib/python2.7/re.py", line 155, in sub
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |     return _compile(pattern, flags).sub(repl, string, count)
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |   File "/usr/local/lib/python2.7/re.py", line 291, in filter
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |     return sre_parse.expand_template(template, match)
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |   File "/usr/local/lib/python2.7/sre_parse.py", line 859, in expand_template
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    |     raise error, "unmatched group"
task-server_celery_prefork_bulk.5.t35bxa1xx0m2@debian    | error: unmatched group
```

**Comment by mlissner** [comment]
And one more related:

```
a61ff565d24d] raised unexpected: error('invalid group reference',)
task-server_celery_prefork_bulk.2.7bxh2wws6v55@debian    | Traceback (most recent call last):
task-server_celery_prefork_bulk.2.7bxh2wws6v55@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 385, in trace_task
task-server_celery_prefork_bulk.2.7bxh2wws6v55@debian    |     R = retval = fun(*args, **kwargs)
task-server_celery_prefork_bulk.2.7bxh2wws6v55@debian    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
task-server_celery_prefork_bulk.2.7bxh2wws6v55@debian    |     return self.run(*args, **kwargs)
task-server_celery_prefork_bulk.2.7bxh2wws6v55@debian    |   File "/opt/celery/cl/citations/tasks.py", line 130, in find_citations_for_opinion_by_pks
task-server_celery_prefork_bulk.2.7bxh2wws6v55@debian    |     opinion.html_with_citations = create_cited_html(opinion, citations)
task-server_celery_prefork_bulk.2.7bxh2wws6v55@debian    |   File "/opt/celery/cl/citations/tasks.py", line 85, in create_cited_html
task-server_celery_prefork_bulk.2.7bxh2wws6v55@debian    |     inner_html = re.sub(citation.as_regex(), repl, inner_html)
task-server_celery_prefork_bulk.2.7bxh2wws6v55@debian    |   File "/usr/local/lib/python2.7/re.py", line 155, in sub
task-server_celery_prefork_bulk.2.7bxh2wws6v55@debian    |     return _compile(pattern, flags).sub(repl, string, count)
task-server_celery_prefork_bulk.2.7bxh2wws6v55@debian    |   File "/usr/local/lib/python2.7/re.py", line 291, in filter
task-server_celery_prefork_bulk.2.7bxh2wws6v55@debian    |     return sre_parse.expand_template(template, match)
task-server_celery_prefork_bulk.2.7bxh2wws6v55@debian    |   File "/usr/local/lib/python2.7/sre_parse.py", line 861, in expand_template
task-server_celery_prefork_bulk.2.7bxh2wws6v55@debian    |     raise error, "invalid group reference"
task-server_celery_prefork_bulk.2.7bxh2wws6v55@debian    | error: invalid group reference
```
