### ISSUE TITLE
Add new search engine for RECAP alerts to Solr

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1236]
RECAP alerts need to be fast because they're going to be popular. To accomplish that, we need to make a sidecar search engine that only has a few day's worth of RECAP content in it. 

I think the speed of such an engine will be fast enough that we could probably provide realtime alerts for thousands of users, but let's not get ahead of ourselves.

**Comment by mlissner** [comment]
So far so good, but not quite there yet. I was able to create the new core by copy/pasting the conf of the RECAP core, and I was able to create a testing core that way too. Once that was created, I created a new version of the docker image and deployed it as in the README. I also updated git to get the latest core configurations.

So far so good.

However, my next step was to verify that the core itself was created on disk. I checked using:

```python
nodes = get_solr_core_status()
print tostring(nodes, pretty_print=True)
```

Which returned an XML node noting that the core was not loaded (`isloaded=False`). I figured it needed a little kick, so I went back to my dev machine and tried to see what would load the core there (my dev machine also reported `isloaded=false`). 

My plan was to try to add some data to it and then watch for it to show up on disk. In dev, I did the following, at which point the core showed up on disk and stopped showing isloaded=false:

```python
import scorched
si = scorched.SolrInterface('http://cl-solr:8983/solr/recap_alerts', mode='w')
```

Boom! 

So I tried to do that on the server, but got an error. Looks like it's probably a permissions error, I'm not sure:

```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 500 {msg=Unable to create core [recap_alerts],trace=org.apache.solr.common.SolrException: Unable to create core [recap_alerts]
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:507)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:466)
	at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:763)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:299)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:207)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:368)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:942)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1004)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
	at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.common.SolrException: Cannot create directory: /var/opt/solr/indices/recap_alerts/index
	at org.apache.solr.core.SolrCore.&lt;init&gt;(SolrCore.java:881)
	at org.apache.solr.core.SolrCore.&lt;init&gt;(SolrCore.java:654)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:491)
	... 29 more
Caused by: java.io.IOException: Cannot create directory: /var/opt/solr/indices/recap_alerts/index
	at org.apache.lucene.store.NativeFSLock.obtain(NativeFSLockFactory.java:143)
	at org.apache.lucene.store.Lock.obtain(Lock.java:77)
	at org.apache.lucene.index.IndexWriter.&lt;init&gt;(IndexWriter.java:755)
	at org.apache.solr.update.SolrIndexWriter.&lt;init&gt;(SolrIndexWriter.java:77)
	at org.apache.solr.update.SolrIndexWriter.create(SolrIndexWriter.java:64)
	at org.apache.solr.core.SolrCore.initIndex(SolrCore.java:531)
	at org.apache.solr.core.SolrCore.&lt;init&gt;(SolrCore.java:785)
	... 31 more
,code=500}</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /solr/recap_alerts/schema. Reason:
<pre>    {msg=Unable to create core [recap_alerts],trace=org.apache.solr.common.SolrException: Unable to create core [recap_alerts]
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:507)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:466)
	at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:763)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:299)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:207)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:368)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:942)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1004)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
	at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.common.SolrException: Cannot create directory: /var/opt/solr/indices/recap_alerts/index
	at org.apache.solr.core.SolrCore.&lt;init&gt;(SolrCore.java:881)
	at org.apache.solr.core.SolrCore.&lt;init&gt;(SolrCore.java:654)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:491)
	... 29 more
Caused by: java.io.IOException: Cannot create directory: /var/opt/solr/indices/recap_alerts/index
	at org.apache.lucene.store.NativeFSLock.obtain(NativeFSLockFactory.java:143)
	at org.apache.lucene.store.Lock.obtain(Lock.java:77)
	at org.apache.lucene.index.IndexWriter.&lt;init&gt;(IndexWriter.java:755)
	at org.apache.solr.update.SolrIndexWriter.&lt;init&gt;(SolrIndexWriter.java:77)
	at org.apache.solr.update.SolrIndexWriter.create(SolrIndexWriter.java:64)
	at org.apache.solr.core.SolrCore.initIndex(SolrCore.java:531)
	at org.apache.solr.core.SolrCore.&lt;init&gt;(SolrCore.java:785)
	... 31 more
,code=500}</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                

</body>
</html>
```

You can see in there though that it was unable to `create directory: /var/opt/solr/indices/recap_alerts/index`. Not sure if that's in the docker container or on the local disk. That's the next piece of the puzzle.

**Comment by mlissner** [comment]
This won't be done in Solr anymore. Closing. We'll open something new when we do Elastic Search.
