### ISSUE TITLE
Automated tests failing and I can't reproduce locally

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1310]
This is eating my week and making me really sad. Look at Github Actions to see a bunch of failing tests. Even master is now failing, which is bonkers, because the same commit was previously working! I just re-ran the tests on master to see if they'd start to fail and sure enough they did. 

So...it's not our code. There are a few things that can change under the hood though between master and my local set up:

 - Our docker images are frozen
 - The code is the same
 - Selenium, redis, and postgresql docker images can change

I think I have the same images as in Github. I did a docker pull, then docker stop, docker rm, and things are still screwy. I'm going to try a few more aggressive things locally to nuke my docker, and if that doesn't work I"m going to make a branch where I can hopefully start debugging this more efficiently.

**Comment by mlissner** [comment]
OK, I compared the images I have locally vs those remote and they're the same, with tests still failing: https://github.com/freelawproject/courtlistener/runs/759968907?check_suite_focus=true

**Comment by mlissner** [comment]
The selenium test cases take screenshots when they fail. Based on those and their stacktraces, it looks like we're getting 500 errors during some of the tests. I can't imagine why.

**Comment by mlissner** [comment]
I mean, it's the same code. I confirmed that. And this doesn't happen locally. So...how can the same code fail in once place and work in the other? 

I'd get if this was a selenium thing. It has all kinds of wonkiness. But it's not, it's a our code that's failing. 

One thing that can be different is our settings. Mine are a *bit* customized. I'll try using the default settings locally and see if things fail.

**Comment by mlissner** [comment]
Nope, that didn't help either. Still things more or less work locally while they fail in CI. WTF.

**Comment by mlissner** [comment]
I think I need to take a look at the 500 errors that are happening. These are the failing stacktraces:

There's a lot of this (it repeats a zillion times, but doesn't say what's causing it):

```
Traceback (most recent call last):
2020-06-10T23:24:49.3526584Z   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
2020-06-10T23:24:49.3526740Z     response = get_response(request)
2020-06-10T23:24:49.3527103Z   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
2020-06-10T23:24:49.3527492Z     response = self.process_exception_by_middleware(e, request)
2020-06-10T23:24:49.3527890Z   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
2020-06-10T23:24:49.3528049Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2020-06-10T23:24:49.3528421Z   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
2020-06-10T23:24:49.3528574Z     response = view_func(request, *args, **kwargs)
2020-06-10T23:24:49.3528717Z   File "/opt/courtlistener/cl/lib/ratelimiter.py", line 43, in wrapper
2020-06-10T23:24:49.3528842Z     return ratelimited_view(request, *args, **kwargs)
2020-06-10T23:24:49.3529186Z   File "/usr/local/lib/python2.7/site-packages/ratelimit/decorators.py", line 30, in _wrapped
2020-06-10T23:24:49.3529484Z     return fn(*args, **kw)
2020-06-10T23:24:49.3529612Z   File "/opt/courtlistener/cl/search/views.py", line 391, in show_results
2020-06-10T23:24:49.3530703Z     return render(request, "homepage.html", render_dict)
2020-06-10T23:24:49.3531365Z   File "/usr/local/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
2020-06-10T23:24:49.3531516Z     content = loader.render_to_string(template_name, context, request, using=using)
2020-06-10T23:24:49.3531861Z   File "/usr/local/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
2020-06-10T23:24:49.3532001Z     return template.render(context, request)
2020-06-10T23:24:49.3532321Z   File "/usr/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
2020-06-10T23:24:49.3532457Z     return self.template.render(context)
2020-06-10T23:24:49.3532774Z   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 207, in render
2020-06-10T23:24:49.3532906Z     return self._render(context)
2020-06-10T23:24:49.3533236Z   File "/usr/local/lib/python2.7/site-packages/django/test/utils.py", line 107, in instrumented_test_render
2020-06-10T23:24:49.3533375Z     return self.nodelist.render(context)
2020-06-10T23:24:49.3533880Z   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
2020-06-10T23:24:49.3534015Z     bit = node.render_annotated(context)
2020-06-10T23:24:49.3534347Z   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
2020-06-10T23:24:49.3534466Z     return self.render(context)
2020-06-10T23:24:49.3534947Z   File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
2020-06-10T23:24:49.3535104Z     return compiled_parent._render(context)
2020-06-10T23:24:49.3535473Z   File "/usr/local/lib/python2.7/site-packages/django/test/utils.py", line 107, in instrumented_test_render
2020-06-10T23:24:49.3535611Z     return self.nodelist.render(context)
2020-06-10T23:24:49.3535936Z   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
2020-06-10T23:24:49.3536081Z     bit = node.render_annotated(context)
2020-06-10T23:24:49.3536597Z   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
2020-06-10T23:24:49.3536736Z     return self.render(context)
2020-06-10T23:24:49.3537059Z   File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
2020-06-10T23:24:49.3537202Z     result = block.nodelist.render(context)
2020-06-10T23:24:49.3537534Z   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
2020-06-10T23:24:49.3537678Z     bit = node.render_annotated(context)
2020-06-10T23:24:49.3538025Z   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
2020-06-10T23:24:49.3538167Z     return self.render(context)
2020-06-10T23:24:49.3538695Z   File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 216, in render
2020-06-10T23:24:49.3538956Z     nodelist.append(node.render_annotated(context))
2020-06-10T23:24:49.3539327Z   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
2020-06-10T23:24:49.3539446Z     return self.render(context)
2020-06-10T23:24:49.3539777Z   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 1040, in render
2020-06-10T23:24:49.3539923Z     output = self.filter_expression.resolve(context)
2020-06-10T23:24:49.3540255Z   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 708, in resolve
2020-06-10T23:24:49.3540401Z     obj = self.var.resolve(context)
2020-06-10T23:24:49.3540735Z   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 849, in resolve
2020-06-10T23:24:49.3540876Z     value = self._resolve_lookup(context)
2020-06-10T23:24:49.3541217Z   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 890, in _resolve_lookup
2020-06-10T23:24:49.3541357Z     current = getattr(current, bit)
2020-06-10T23:24:49.3541478Z   File "/opt/courtlistener/cl/visualizations/models.py", line 109, in json
2020-06-10T23:24:49.3541615Z     return self.json_versions.all()[0].json_data
2020-06-10T23:24:49.3541965Z   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 289, in __getitem__
2020-06-10T23:24:49.3542102Z     return list(qs)[0]
2020-06-10T23:24:49.3542225Z IndexError: list index out of range
```

And then there's this:

```
2020-06-10T23:24:53.5186273Z F..........
2020-06-10T23:24:53.5186824Z ======================================================================
2020-06-10T23:24:53.5187220Z ERROR: test_search_based_opinion_feed (cl.tests.test_feeds.FeedsFunctionalTest)
2020-06-10T23:24:53.5188151Z ----------------------------------------------------------------------
2020-06-10T23:24:53.5188472Z Traceback (most recent call last):
2020-06-10T23:24:53.5189007Z   File "/usr/local/lib/python2.7/site-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function
2020-06-10T23:24:53.5189337Z     return function(*args, **kwargs)
2020-06-10T23:24:53.5189612Z   File "/opt/courtlistener/cl/tests/test_feeds.py", line 175, in test_search_based_opinion_feed
2020-06-10T23:24:53.5189881Z     self.browser.find_element_by_id("id_q").send_keys("bonvini")
2020-06-10T23:24:53.5190430Z   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
2020-06-10T23:24:53.5190740Z     return self.find_element(by=By.ID, value=id_)
2020-06-10T23:24:53.5191547Z   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
2020-06-10T23:24:53.5192116Z     'value': value})['value']
2020-06-10T23:24:53.5192677Z   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
2020-06-10T23:24:53.5192984Z     self.error_handler.check_response(response)
2020-06-10T23:24:53.5193515Z   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
2020-06-10T23:24:53.5193837Z     raise exception_class(message, screen, stacktrace)
2020-06-10T23:24:53.5194122Z NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"id_q"}
2020-06-10T23:24:53.5194383Z   (Session info: chrome=83.0.4103.61)
2020-06-10T23:24:53.5194985Z   (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Linux 5.3.0-1022-azure x86_64)
2020-06-10T23:24:53.5195234Z 
2020-06-10T23:24:53.5195436Z 
2020-06-10T23:24:53.5195682Z ======================================================================
2020-06-10T23:24:53.5195954Z ERROR: test_anonymous_user_is_prompted_when_favoriting_an_opinion (cl.favorites.tests.UserFavoritesTest)
2020-06-10T23:24:53.5196440Z ----------------------------------------------------------------------
2020-06-10T23:24:53.5196728Z Traceback (most recent call last):
2020-06-10T23:24:53.5197442Z   File "/usr/local/lib/python2.7/site-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function
2020-06-10T23:24:53.5197741Z     return function(*args, **kwargs)
2020-06-10T23:24:53.5197996Z   File "/opt/courtlistener/cl/favorites/tests.py", line 83, in test_anonymous_user_is_prompted_when_favoriting_an_opinion
2020-06-10T23:24:53.5198265Z     search_box = self.browser.find_element_by_id("id_q")
2020-06-10T23:24:53.5198802Z   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
2020-06-10T23:24:53.5199219Z     return self.find_element(by=By.ID, value=id_)
2020-06-10T23:24:53.5199813Z   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
2020-06-10T23:24:53.5200290Z     'value': value})['value']
2020-06-10T23:24:53.5200853Z   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
2020-06-10T23:24:53.5201218Z     self.error_handler.check_response(response)
2020-06-10T23:24:53.5201760Z   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
2020-06-10T23:24:53.5202060Z     raise exception_class(message, screen, stacktrace)
2020-06-10T23:24:53.5202341Z NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"id_q"}
2020-06-10T23:24:53.5202626Z   (Session info: chrome=83.0.4103.61)
2020-06-10T23:24:53.5203218Z   (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Linux 5.3.0-1022-azure x86_64)
2020-06-10T23:24:53.5203486Z 
2020-06-10T23:24:53.5204100Z 
2020-06-10T23:24:53.5204351Z ======================================================================
2020-06-10T23:24:53.5204640Z ERROR: test_logged_in_user_can_save_favorite (cl.favorites.tests.UserFavoritesTest)
2020-06-10T23:24:53.5205156Z ----------------------------------------------------------------------
2020-06-10T23:24:53.5205490Z Traceback (most recent call last):
2020-06-10T23:24:53.5206008Z   File "/usr/local/lib/python2.7/site-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function
2020-06-10T23:24:53.5206313Z     return function(*args, **kwargs)
2020-06-10T23:24:53.5206581Z   File "/opt/courtlistener/cl/favorites/tests.py", line 141, in test_logged_in_user_can_save_favorite
2020-06-10T23:24:53.5206828Z     search_box = self.browser.find_element_by_id("id_q")
2020-06-10T23:24:53.5207515Z   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
2020-06-10T23:24:53.5207846Z     return self.find_element(by=By.ID, value=id_)
2020-06-10T23:24:53.5208407Z   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
2020-06-10T23:24:53.5208911Z     'value': value})['value']
2020-06-10T23:24:53.5209453Z   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
2020-06-10T23:24:53.5209800Z     self.error_handler.check_response(response)
2020-06-10T23:24:53.5210414Z   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
2020-06-10T23:24:53.5210718Z     raise exception_class(message, screen, stacktrace)
2020-06-10T23:24:53.5210997Z NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"id_q"}
2020-06-10T23:24:53.5211280Z   (Session info: chrome=83.0.4103.61)
2020-06-10T23:24:53.5211867Z   (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Linux 5.3.0-1022-azure x86_64)
2020-06-10T23:24:53.5212138Z 
2020-06-10T23:24:53.5212332Z 
2020-06-10T23:24:53.5212572Z ======================================================================
2020-06-10T23:24:53.5212820Z FAIL: test_user_can_change_favorites (cl.favorites.tests.UserFavoritesTest)
2020-06-10T23:24:53.5213481Z ----------------------------------------------------------------------
2020-06-10T23:24:53.5213760Z Traceback (most recent call last):
2020-06-10T23:24:53.5214310Z   File "/usr/local/lib/python2.7/site-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function
2020-06-10T23:24:53.5214616Z     return function(*args, **kwargs)
2020-06-10T23:24:53.5214881Z   File "/opt/courtlistener/cl/favorites/tests.py", line 253, in test_user_can_change_favorites
2020-06-10T23:24:53.5215206Z     self.assertEqual(profile_dropdown.text.strip(), u"Profile")
2020-06-10T23:24:53.5215647Z AssertionError: u'Opinions' != u'Profile'
2020-06-10T23:24:53.5216594Z - Opinions
2020-06-10T23:24:53.5217134Z + Profile
```

**Comment by mlissner** [comment]
So @ikeboy identified that this is caused by a couple lines of code in models.py:

```
    @property
    def json(self):
        """Returns the most recent version"""
        return self.json_versions.all()[0].json_data
```

That gets called from the template and crashes it when you have a visualization but it doesn't have any JSON data. 

So now the question is: How did such a visualization get created and can we fix that? The lines of code above haven't been changed in five years.
