### ISSUE TITLE
Upgrade to next LTS version of Ubuntu (16.04)

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1421]
I'm following instructions [here][xenial]. A couple notes:

1. It's not happy that I'm doing this over SSH, and it opened a fresh SSH thing on port 1022, I think. 

1. It says it disabled third party sources. 

1. It restarted postgres, postfix, ssh, nfs, and one other.

To test after:

1. Apache: https://www.courtlistener.com/

1. Redis: https://www.courtlistener.com/monitoring/redis-writes/

1. Disks: `cat /proc/mdstat`

1. NFS: Get file from other server.

1. Postfix: Create new account

1. Supervisord:

[xenial]: https://wiki.ubuntu.com/XenialXerus/ReleaseNotes

**Comment by mlissner** [comment]
This went...super smoothly! I did it over SSH with @brianwc standing by. No major issues. Worst thing that happened was that `supervisor` wouldn't start any daemons, and instead had an error that said "ERROR (spawn error)". I tried to run the script that the daemon runs manually, and it showed an error that:

```
↪ cl && sudo -H -u www-data ../.virtualenvs/courtlistener/bin/python ./manage.py scrape_rss --help
[sudo] password for mlissner: 
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/__init__.py", line 3, in <module>
    from django.utils.version import get_version
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/utils/version.py", line 3, in <module>
    import datetime
ImportError: No module named datetime
```

That's weird! I googled that, and there were a lot of results, but this one seemed best:

https://askubuntu.com/a/556068/324

It says to:

    cd $VIRTUAL_ENV
    virtualenv .

Which worked, though it freaked me out. I think we're in business. Total downtime: about 20 minutes.

**Comment by mlissner** [comment]
I have photos of various logs where settings files were diffed or whatever. Done.
