### ISSUE TITLE
iQuery crawler unhappy about unseekable streams

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1447]
I mean, I linked our log file to /dev/stdout, but that's exactly what Nginx's official docket image does. Apparently Python is none too pleased about that idea. Anyway, here's a trace. I think it's fixed, but let's be sure:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/handlers.py", line 69, in emit
    if self.shouldRollover(record):
  File "/usr/local/lib/python3.8/logging/handlers.py", line 186, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
io.UnsupportedOperation: underlying stream is not seekable
Call stack:
  File "/opt/courtlistener/manage.py", line 15, in <module>
    main()
  File "/opt/courtlistener/manage.py", line 11, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/courtlistener/cl/recap/management/commands/pacer_iquery_scraper.py", line 119, in handle
    logger.info(
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1434, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/logging.py", line 85, in sentry_patched_callhandlers
    return old_callhandlers(self, record)
Message: 'iQuery crawling starting up. Will crawl %s dockets'
Arguments: (14399,)
```

**Comment by mlissner** [comment]
cc: @ikeboy.

**Comment by mlissner** [comment]
Ditto for `upload_to_ia` script.

**Comment by mlissner** [comment]
FWIW, I'm not sure this is stopping the script from running. I think it just breaks logging.

**Comment by ikeboy** [comment]
Script doesn't seem to have run since Nov 4th.

**Comment by ikeboy** [comment]
iquery works with the latest commits on my machine, although upgrading seems to have wiped my local django database and scraping rss doesn't seem to do anything so hard to populate it with data to test with.

**Comment by mlissner** [comment]
Hm, I wonder if new versions of postgresql's docker image wipe the DB. I don't think I've experienced that, but I'm not sure if I'd notice.

Good to see that it's working though, at least locally. We're squishing a lot of bugs right now.

**Comment by mlissner** [comment]
This is fixed, but iquery remains unhappy, as you can see in #1468. Progress continues there.
