### ISSUE TITLE
Bulk data broken due to funky filepaths in docker

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1527]
Our current bulk data code is written with the assumption that all our machines have a bulk storage area in the same location. That was true for a time, but now that we've dockerized, it no longer is. The task images have storage at `/storage`, the main server still has it at `/sata`, etc. 

The code needs to be re-done a bit to make it so that tasks use the correct directories and so the main server does too.

I actually did the opposite of this a while back, in https://github.com/freelawproject/courtlistener/commit/9b74aee753c08ddedb926e4e26fd88413fdd02f4.

Ultimately, `settings.BULK_DATA_DIR` needs to be used properly by tasks and scripts.

**Comment by mlissner** [comment]
Meant to include the stacktrace, in case it's helpful:

```
INFO Starting bulk file creation with 11 celery tasks...
 - Creating bulk clusters files...
Traceback (most recent call last):
  File "/opt/courtlistener/manage.py", line 15, in <module>
    main()
  File "/opt/courtlistener/manage.py", line 11, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/courtlistener/cl/api/management/commands/cl_make_bulk_data.py", line 118, in handle
    make_bulk_data_and_swap_it_in(
  File "/usr/local/lib/python3.8/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 393, in __call__
    return self.run(*args, **kwargs)
  File "/opt/courtlistener/cl/lib/timer.py", line 11, in wrapper
    res = func(*arg)
  File "/opt/courtlistener/cl/api/tasks.py", line 26, in make_bulk_data_and_swap_it_in
    num_written = write_json_to_disk(courts, bulk_dir=tmp_bulk_dir, **kwargs)
  File "/opt/courtlistener/cl/api/tasks.py", line 123, in write_json_to_disk
    history.add_current_attempt_and_save()
  File "/opt/courtlistener/cl/api/utils.py", line 432, in add_current_attempt_and_save
    self.save_to_disk()
  File "/opt/courtlistener/cl/api/utils.py", line 401, in save_to_disk
    mkdir_p(self.path.rsplit("/", 1)[0])
  File "/opt/courtlistener/cl/lib/utils.py", line 48, in mkdir_p
    os.makedirs(path)
  File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/courtlistener/cl/assets/media/bulk-data/tmp'
```

There also appears to be a Sentry issue for this, but I haven't tracked it down.
