### ISSUE TITLE
Implement intrusion detection systems

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1574]
After our big scare a few weeks ago, I've been doing a lot of research on how to prepare for the possibility that somebody actually *does* gain access to our servers. This is a big industry and it's taken a bit of work to figure out what's a reasonable solution. Some candidates and notes:

 - **[Snort](https://www.snort.org)** 

    This is a network based Intrusion Detection System. From what I can tell, it watches the network for weird patterns and sends alerts when it sees things it doesn't like. This one looks like it'd be very powerful on something like our router (and @brianwc suggested it too), but I decided against it because it looked too complicated, and because I didn't feel like it was quite solving the problem I wanted. I feel like monitoring our network could be a good part of the puzzle, but that with HTTPS on so many things, it might be a pain, and I didn't thrill at having a utility in the middle of our all our traffic slowing it down, possibly breaking it, etc.
 
- **[Tripwire](https://github.com/Tripwire/tripwire-open-source)**
 
    This is a system that monitors various things on the system to see if they change. In particular, it monitors binaries, and watches for things like rootkits. I actually appreciated the simplicity of it (it doesn't require its own server, for example), but after spending a day with it trying to get it in place, I concluded that it's a full time job monitoring it and updating it. 

    For example, after I got it all set up, it triggered *itself*, because its own files changed. So I guess I could make a rule to exclude its own files...OTOH, those files are supposed to be monitored so nobody can mess with tripwire and thus disable it, so the real solution isn't to exclude those files, but rather to update the DB of file hashes to have the new values. That's doable, but then the next day I got an email saying that a bunch of binary files had changed. Why? Because of an automated OS update. And guess what? Until I go and update the hash DB, I'm going to keep getting alerts every 24 hours about these same files. 

    I also found that the documentation for tripwire was exceedingly old, and exceedingly bad. Like, when you install it, it creates a cronjob, which is fine, but all the docs tell you to create one, so I did that too. Now we have two. The official docs are just a readme, and the tutorials around are all 10-20 years old. The command line flags are weird, etc. Anyway, it's just kind of a cruddy ecosystem.

 - **[OSSEC](https://ossec.net)**

    This one bills itself as a mega compliance system, and I believe it. They give the impression that their software used by tens of thousands of large organizations. It might be too much for us, but after our scare, I realized that, well, actually, we have a lot of enemies, and we should be prepared. 

    I have spent a lot of time working on this as of now, and I think it's nearly ready. It does most, if not all, of the things that Tripwire does, but through a distributed architecture where there's a manager on a new server we run ($20/month), and there are agents on our servers that send it logs and whatnot. So far, it's OK, though I found two bugs in the installation instructions, sigh. My PRs for both have been merged though, which is a good sign of life. This is the winning tool right now, so I'll write more about it below.

 - **[Wazuh](https://documentation.wazuh.com/)**

    This one bills itself as a fork of OSSEC, and boy is it ever. It uses a similar manager-agent architecture, but builds the whole thing on the ELK stack (ElasticSearch, LogStash, Kibana). I don't know that stack, but I appreciate that Wazuh has a nice website where you can see stuff. That's neat. There's a hosted version of this but even with a big non-profit discount, it's still $250/month — too much for us. 

    Still, I liked it in concept, and I spent a bunch of time getting the self-hosted version set up in AWS Lightsail, but as soon as  I did a new version came out. When I tried to install that via apt, a bunch of files had changed and needed manual diffs. After that, it wouldn't start again. I asked how to get it going again on their forum, and apparently I have to run some command to fix a port access issue that Kibana has. UGH. I'm just glad that the update was now and not in a month. I think this would be a full time dev-ops project. Nope.

 - **[Canaries](https://canary.tools/)**

    These are *really* cool. The basic idea is that you put a little piece of hardware in your network that looks like a server of some kind. If anything ever tries to do something with it (port scan, login, whatever), it sends an alert. A friend tells me that in Heroku these caught red teams regularly. Awesome! Only problem: They're too expensive. Maybe there's an open source version somewhere.

Where things stand:

1. I need to uninstall Tripwire from our main server. It's annoying.
2. I need to nuke the Wazuh server, DNS, and agent. once OSSEC looks like it'll work.
3. OSSEC is a royal, huge PITA to get set up, but mostly that's because sending an email is really GD hard. I've got that working though, so now I need to get the agents working properly from our servers.
4. I'd like an open source canary tool that we can use. More research needed.

**Comment by mlissner** [comment]
I spent a bunch of time getting tripwire and Wazuh working, but I'm just not going to document that since OSSEC seems to have won this round. 

Tripwire and Wazuh agents are now both uninstalled:

```
sudo apt-get purge tripwire
sudo apt-get purge wazuh-agent
sudo rm /etc/apt/sources.list.d/wazuh.list 
```



Getting OSSEC installed is pretty straightforward, though it needs an email server, and that part is quite hard.

**Comment by mlissner** [comment]
After spending awhile yesterday getting postfix up and running (mostly), I learned that AWS's SES product provides SMTP servers, and I spent the day getting them to work. The general architecture is that you configure OSSEC to connect to a local postfix server. That postfix server is configured as a relay, and it connects to AWS SES to do the actual sending of messages. In a better world, OSSEC would connect directly to SES's SMTP endpoints, but no.

Getting AWS SES set up properly wasn't too bad and will be easier in the future. The [basic instructions are here](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-smtp.html).  You have to verify the domain, verify your senders, and like that. 

Getting postfix set up to connect to SES was a pain. The general idea is in the [Wazuh docs](https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/smtp_authentication.html), so that's a good place to start, but that only gets things working with a valid Gmail address. The general process I took was to set things up using those instructions, then enhance the configuration using [mozilla's configuration tool](https://ssl-config.mozilla.org/#server=postfix&version=3.4.13&config=modern&openssl=1.1.1f&guideline=5.6), [Let's Encrypt's tool for creating a standalone certificate](https://certbot.eff.org/lets-encrypt/ubuntufocal-other), and [AWS's guide for SASL authentication](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/postfix.html).

A couple things to note:

 - Doing let's encrypt was fine, but because it's not a web server, I did the DNS verification thing. That's fine, but I had to mess with our IAM policy to add the free.law hosted zone to the allowed zones that the letsencrypt user could mess with.
 - We have Certificate Authority Authorization (CAA) set up for free.law, so I had [to tweak that](https://letsencrypt.org/docs/caa/) to allow letsencrypt.org.

Once all of the above was done, things seem to be working via a test like:

    echo "body of email" | mail -s "subject line, yo" mike@free.law

So that's that. I think in the future we'll probably want to move to using SES more for sending emails from CL instead of hosting our own server, but not just yet. 

Now to make OSSEC actually do something.

**Comment by mlissner** [comment]
OK, one more tweak. I had to make the change listed here so that postfix would accept emails from ossec: https://www.linode.com/community/questions/19815/ossec-cant-send-email-but-postfix-and-mailx-work-fine.

**Comment by mlissner** [comment]
OK, OSSEC is all set for now, though I'll spend some time dialing it in. A few things to mention:

1. Installing agents is easy; follow the directions. Once installed, the one command that's helpful that's not obviously documented is:
    ```
    root@ossec:/home/ubuntu# /var/ossec/bin/list_agents -c
    web-server-any is active.
    mega-server-any is active.
    ```
    That works really nicely on the manager to make sure everything is working.
 
2. The defaults are pretty good, I think, except that it's worth turning on `realtime` filechecking in the agent configs (`/var/ossec/etc/ossec.conf`)

3. You'll note that all the configs and logs and whatnot for ossec are in /var/ossec. This must be a security thing.

4. The hardest part about this was ① analyzing the different offerings, and ② installing the email server. 

The last piece of this is to check out if there are any good canary offerings.

**Comment by mlissner** [comment]
Getting some interesting alerts. For example, it caught that we were low on disk space, whereas munin is so noisy about SMART stuff that I had missed it. Alas, one alert is triggering too much, so I had to override it in `/var/ossec/rules/local_rules.xml` on the manager.

**Comment by mlissner** [comment]
Hm, so Let's Encrypt warned me today that our certificate was about to expire. I dug into it and found the following error (and similar) in /var/log/letsencrypt: 

```
Traceback (most recent call last):
  File "/snap/certbot-dns-route53/current/lib/python3.8/site-packages/certbot_dns_route53/_internal/dns_route53.py", line 57, in perform
    change_ids = [
  File "/snap/certbot-dns-route53/current/lib/python3.8/site-packages/certbot_dns_route53/_internal/dns_route53.py", line 58, in <listcomp>
    self._change_txt_record("UPSERT",
  File "/snap/certbot-dns-route53/current/lib/python3.8/site-packages/certbot_dns_route53/_internal/dns_route53.py", line 108, in _change_txt_record
    zone_id = self._find_zone_id_for_domain(validation_domain_name)
  File "/snap/certbot-dns-route53/current/lib/python3.8/site-packages/certbot_dns_route53/_internal/dns_route53.py", line 86, in _find_zone_id_for_domain
    for page in paginator.paginate():
  File "/snap/certbot-dns-route53/current/lib/python3.8/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/snap/certbot-dns-route53/current/lib/python3.8/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/snap/certbot-dns-route53/current/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/snap/certbot-dns-route53/current/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListHostedZones operation: User: XXX is not authorized to perform: route53:ListHostedZones
```

The user role says something about LightSail, which I think means it's getting the role from the server itself rather than the credential file. 

Looking in /etc/cron.d/certbot, the config has something like:

```
* * * * SOME_VAR=/path/to/aws/config.ini certbot renew
```

I'd expect that to work, but since it didn't seem to, I reorganized the file to put SOME_VAR at the top. Hopefully that'll fix it. If not, we'll get another warning email from Let's Encrypt. 

Next time, if this happens again, we can just put the config file where it looks by default (check the Let's Encrypt DNS connector thing for details about that).
