### ISSUE TITLE
Tennessee tests are not running b/c wrongly named

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1665]
In `cl.opinion_page.tests` there's a class for `UploadPublication`. Alas, it does not end with the word "Test", so these tests don't ever get run. This class should be named properly and the tests fixed if necessary. 

Right now, they're failing on my branch with this:

```txt
↪ docker exec -it -e SELENIUM_DEBUG=1 -e SELENIUM_TIMEOUT=30 cl-django python /opt/courtlistener/manage.py test cl.opinion_page.tests.UploadPublicationTest --verbosity=1 --keepdb
Using existing test database for alias 'default'...
Cache table 'django_cache' already exists.
System check identified no issues (0 silenced).
/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1367: RuntimeWarning: DateTimeField Person.date_created received a naive datetime (2020-07-16 17:58:34.127705) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"
/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1367: RuntimeWarning: DateTimeField Person.date_modified received a naive datetime (2020-07-16 17:58:34.127752) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"
/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1367: RuntimeWarning: DateTimeField Position.date_created received a naive datetime (2020-07-16 17:58:34.147217) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"
/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1367: RuntimeWarning: DateTimeField Position.date_modified received a naive datetime (2020-07-16 17:58:34.147252) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"
/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1367: RuntimeWarning: DateTimeField Source.date_created received a naive datetime (2020-07-16 17:58:34.151991) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"
/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1367: RuntimeWarning: DateTimeField Source.date_modified received a naive datetime (2020-07-16 17:58:34.152023) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"
EEEEEEEE
======================================================================
ERROR: test_access_upload_page (cl.opinion_page.tests.UploadPublicationTest)
Can we successfully access upload page with access?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/courtlistener/cl/opinion_page/tests.py", line 213, in setUp
    tenn_group = Group.objects.get(name="tenn_work_uploaders")
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.

======================================================================
ERROR: test_form_save (cl.opinion_page.tests.UploadPublicationTest)
Can we saves successfully to db?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/courtlistener/cl/opinion_page/tests.py", line 213, in setUp
    tenn_group = Group.objects.get(name="tenn_work_uploaders")
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.

======================================================================
ERROR: test_handle_duplicate_pdf (cl.opinion_page.tests.UploadPublicationTest)
Can we validate PDF not in system?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/courtlistener/cl/opinion_page/tests.py", line 213, in setUp
    tenn_group = Group.objects.get(name="tenn_work_uploaders")
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.

======================================================================
ERROR: test_pdf_upload (cl.opinion_page.tests.UploadPublicationTest)
Can we upload a PDF and form?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/courtlistener/cl/opinion_page/tests.py", line 213, in setUp
    tenn_group = Group.objects.get(name="tenn_work_uploaders")
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.

======================================================================
ERROR: test_pdf_validation_failure (cl.opinion_page.tests.UploadPublicationTest)
Can we fail upload documents that are not PDFs?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/courtlistener/cl/opinion_page/tests.py", line 213, in setUp
    tenn_group = Group.objects.get(name="tenn_work_uploaders")
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.

======================================================================
ERROR: test_redirect_without_access (cl.opinion_page.tests.UploadPublicationTest)
Can we successfully redirect individuals without proper access?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/courtlistener/cl/opinion_page/tests.py", line 213, in setUp
    tenn_group = Group.objects.get(name="tenn_work_uploaders")
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.

======================================================================
ERROR: test_required_case_title (cl.opinion_page.tests.UploadPublicationTest)
Can we validate required testing field case title?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/courtlistener/cl/opinion_page/tests.py", line 213, in setUp
    tenn_group = Group.objects.get(name="tenn_work_uploaders")
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.

======================================================================
ERROR: test_tn_wc_app_upload (cl.opinion_page.tests.UploadPublicationTest)
Can we test appellate uplading?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/courtlistener/cl/opinion_page/tests.py", line 213, in setUp
    tenn_group = Group.objects.get(name="tenn_work_uploaders")
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.

----------------------------------------------------------------------
Ran 8 tests in 0.155s

FAILED (errors=8)
```

**Comment by mlissner** [comment]
@flooie can you confirm that this is fixed?

**Comment by mlissner** [comment]
@flooie seeking confirmation again, please, when you get a sec, so we can close this out.
