### ISSUE TITLE
Cannot get files from storage.courtlistener.com using PHP

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1668]
One of our clients uses PHP to access our content and weirdly whenever they do, they get a crash with the following message:

```
Warning: readfile(https://www.courtlistener.com/recap/gov.uscourts.txwd.1099911/gov.uscourts.txwd.1099911.48.0.pdf): failed to open stream: HTTP request failed! HTTP/1.1 503 Service Temporarily Unavailable
```

I was able to install PHP and reproduce this myself using either the readfile command above or curl. The curl commands looked like:

```php
$url = 'https://storage.courtlistener.com/recap/gov.uscourts.dcd.178502/gov.uscourts.dcd.178502.1.0_48.pdf';
$ch = curl_init($url);
$data = curl_exec($ch);
```

And you can make the request more verbose by doing:

```
curl_setopt($ch, CURLOPT_VERBOSE, true);
```

When I ran that, I'd get errors similar to the above.

**Comment by mlissner** [comment]
Eventually, I began to wonder why these requests weren't working while things worked properly from my browser and from Python requests. I had a theory that curl was being blocked by our Web Application Firewall (WAF), and I checked things out there. That was fine, but it had code to block bots that I did disable since it also included blocks from AWS IP addresses, which we don't want to block. I tested the WAF by configuring each rule to "count" requests instead of "block" them. With that done, traffic continued, so it seemed clear that the WAF wasn't the issue.

The next theory was that the request was somehow invalid or otherwise bad, but since I'm not a PHP dev, I didn't have good theories (beyond wireshark, ugh) about how to inspect the requests being made. Eventually, I remembered that httpbin.org can help with this, and I made a request there:

```
02:34:48::mlissner@gabbro::~ 
↪ php -a
Interactive mode enabled

php > $ch = curl_init("https://httpbin.org/headers");
php > $data = curl_exec($ch);
{
  "headers": {
    "Accept": "*/*", 
    "Host": "httpbin.org", 
    "X-Amzn-Trace-Id": "Root=1-6091bf14-64fa15f26b0e4bed430c98f3"
  }
}
```

Interesting. They use AWS. But more interestingly, curl doesn't set a user agent. That's fun, and running this fixed the error on the client side:

```
php > curl_setopt($ch, CURLOPT_USERAGENT, 'foo');
```

Getting somewhere.

**Comment by mlissner** [comment]
Finally, I dug a bit deeper into how to read lambda logs, and I found [this][holy] answer on Stackoverflow, which provided a log query that found errors. I saved the query into Cloudwatch Insights.

Using that query, I quickly saw that our lambda was crashing with:

```
[ERROR] KeyError: 'user-agent' Traceback (most recent call last):
   File "/var/task/lambda_function.py", line 21, in lambda_handler
     if is_og_bot(request) and not og_disabled:
   File "/var/task/bot_detector.py", line 25, in is_og_bot
     return base_bot_matcher(request, known_bots)
   File "/var/task/bot_detector.py", line 7, in base_bot_matcher
     ua = request["headers"]["user-agent"][0].get("value", "Testing U-A")
```

OK, fine. So the solution was that we assumed all requests had a user agent, or that AWS would put a blank one into the headers dict. Bad assumption, easily fixed in a new version of the lambda function. Once fixed, I updated the CloudFront Behavior, waited a minute or so, and all was well.

[holy]: https://stackoverflow.com/a/58976674/64911
