### ISSUE TITLE
Harvard Importer Bug get_or_create

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1848]
I have a confusing bug here.  The importer (only while importing sw3d opinions begins crashing around volumes 420.  

The log is below but the crash appears to happen when adding a citation for an opinion that already is in the system.  We have a unique constraint and all with opinion clusters and citations.  

The problem is the crash here occurs on this method `Citation.objects.get_or_create...`

I was under the impression and still am that get_or_create is a work around from the unique constraint issue.  If its already in existence... get it- if not create it.  Im not sure why this bug is happening now.  But it appears to be happening with regard to opinions that we have scraped from court websites only (in my limited sample size).

@mlissner have you seen this before?

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/courtlistener/manage.py", line 15, in <module>
    main()
  File "/opt/courtlistener/manage.py", line 11, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/courtlistener/cl/corpus_importer/management/commands/harvard_opinions.py", line 1070, in handle
    parse_harvard_opinions(options)
  File "/opt/courtlistener/cl/corpus_importer/management/commands/harvard_opinions.py", line 314, in parse_harvard_opinions
    add_citations(
  File "/opt/courtlistener/cl/corpus_importer/management/commands/harvard_opinions.py", line 497, in add_citations
    Citation.objects.get_or_create(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 576, in get_or_create
    return self._create_object_from_params(kwargs, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 610, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 499, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "search_citation_cluster_id_7a668830aad411f5_uniq"
DETAIL:  Key (cluster_id, volume, reporter, page)=(1039931, 2013, Ark., 305) already exists.

Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Comment by flooie** [comment]
This was a fun one to track down. 

When we import the SW3d reporter for Texas we started importing Arkansas as well.  

Well.. it appears when we start adding citations - if we have the opinion already - if the reporter type is different - the get fails - and the create also fails because the unique constraint.  

Now this apparently appears to be happening because the Arkansas reporter technically ended in 2009 and they went entirely virtual.  But kept the same citation reporter.  But if you look at the reporter page you see it jumps from 

<img width="437" alt="Screen Shot 2022-01-03 at 10 33 00 AM" src="https://user-images.githubusercontent.com/6464529/147949270-ce624799-a5d8-4501-ba16-a9d9a4659969.png">

volume 383 to 2009.  This essentially means we are importing a standard reporter type and then we switch to a neutral cite. This could be a failing of reporters-db (maybe).  

This is also occurring in the Pacific reporter for Oklahoma because we appear to be incorrectly identifying the Oklahoma opinions citations as neutral citations.

**Comment by mlissner** [comment]
I have frustrating memories of tracking down similar get_or_create unique constraint bugs. Good documentation, thanks.

**Comment by flooie** [comment]
This has been resolved in the latest PR
