### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/storage/bulk-data/tmp/dockets/nystateassembly/62987714.json'

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1902]
Completed 8,583,000 items so far.
Traceback (most recent call last):
  File "/opt/courtlistener/manage.py", line 15, in <module>
    main()
  File "/opt/courtlistener/manage.py", line 11, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/courtlistener/cl/api/management/commands/cl_make_bulk_data.py", line 118, in handle
    make_bulk_data_and_swap_it_in(
  File "/usr/local/lib/python3.8/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 393, in __call__
    return self.run(*args, **kwargs)
  File "/opt/courtlistener/cl/lib/timer.py", line 11, in wrapper
    res = func(*arg)
  File "/opt/courtlistener/cl/api/tasks.py", line 32, in make_bulk_data_and_swap_it_in
    num_written = write_json_to_disk(courts, bulk_dir=tmp_bulk_dir, **kwargs)
  File "/opt/courtlistener/cl/api/tasks.py", line 204, in write_json_to_disk
    with open(loc, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/storage/bulk-data/tmp/dockets/nystateassembly/62987714.json'
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

**Comment by flooie** [comment]
[Sentry Issue](https://sentry.io/organizations/freelawproject/issues/3010165496/?project=5257254&query=is%3Aunresolved+bulk&statsPeriod=14d)

**Comment by flooie** [comment]
I would note that there does not appear to be a docket number associated with the case.

**Comment by flooie** [comment]
This crash occurred 3 or 4 days into the bulk process.

**Comment by flooie** [comment]
This should be an easy one to debug, I'm planning to import the ant-np-cas reporter and run the bulk creator again locally

**Comment by flooie** [comment]
@mlissner I suppose it doesn't hurt to do a mkdir ... or catch the error?
