### ISSUE TITLE
Harvard Import Error 

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#2351]
This error is being thrown ... occasionally on imports.  Looks like a change in January is now raising its head.
```
Traceback (most recent call last):
  File "/opt/courtlistener/manage.py", line 15, in <module>
    main()
  File "/opt/courtlistener/manage.py", line 11, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/courtlistener/cl/corpus_importer/management/commands/harvard_opinions.py", line 1141, in handle
    parse_harvard_opinions(options)
  File "/opt/courtlistener/cl/corpus_importer/management/commands/harvard_opinions.py", line 360, in parse_harvard_opinions
    previously_imported_case = find_previously_imported_cases(
  File "/opt/courtlistener/cl/corpus_importer/management/commands/harvard_opinions.py", line 889, in find_previously_imported_cases
    citations__reporter=found_cite[0].corrected_reporter(),
AttributeError: 'IdCitation' object has no attribute 'corrected_reporter'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

There is even a warning in pycharm `Unresolved attribute reference 'corrected_reporter' for class 'CitationBase' `

```
    possible_cases = OpinionCluster.objects.filter(
        citations__reporter=found_cite[0].corrected_reporter(),
        citations__volume=found_cite[0].groups["volume"],
        citations__page=found_cite[0].groups["page"],
    ).order_by("id")
```

**Comment by mlissner** [comment]
Is this a bug in Eyecite?

**Comment by flooie** [comment]
No.  Corrected Reporter is available on almost all citation classes, but it's not available on IdCitation, which makes sense.  Unfortunately, we just now ended up ingesting a handful of gibberish-ish citations that came back as id citations and were causing this error. 

I think the workaround is to check if we have citations and check that the citations are full case law citations.  

Just to square the circle 

```
"citations": [
    {
      "type": "official",
      "cite": "7 Ct. Cl. 65"
    },
    {
      "type": "parallel",
      "cite": "1 Ct. Cls. R., p. 270, 3 id., p. 10; 7 W. R., p. 666"
    }
  ],
```

 this is an example of the failing citation (the parallel cite) which comes back as an ID citation.  Obviously that doesnt seem correct either but I think thats for another issue.
