### ISSUE TITLE
Harvard tests should not hit the network

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3100]
As a general rule, we don't want our tests hitting the network. Instead, they should use mocks to either block the network request entirely (if it's not necessary), or to fake the response if the response is needed.

Case in point, my workflow just failed because a Harvard test tried (and failed) to get something from Github (which is having problems today).

Relevant note:
```
File "/opt/courtlistener/cl/corpus_importer/management/commands/harvard_opinions.py", line 245, in get_fix_list
    data = requests.get(
      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
```

Full trace:

```
======================================================================
ERROR: test_attorney_extraction (cl.corpus_importer.tests.HarvardTests.test_attorney_extraction)
Did we properly parse attorneys?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/usr/local/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/opt/courtlistener/cl/tests/cases.py", line 28, in _callTestMethod
    super()._callTestMethod(method)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/opt/courtlistener/cl/corpus_importer/tests.py", line 779, in test_attorney_extraction
    self.assertSuccessfulParse(1)
    ^^^^^^^^^^^^^^^^^
  File "/opt/courtlistener/cl/corpus_importer/tests.py", line 610, in assertSuccessfulParse
    parse_harvard_opinions(
    ^^^^^^^^^^^^^^^^^
  File "/opt/courtlistener/cl/corpus_importer/management/commands/harvard_opinions.py", line 316, in parse_harvard_opinions
    fix_list = get_fix_list()
      ^^^^^^^^^^^^^^^^^
  File "/opt/courtlistener/cl/corpus_importer/management/commands/harvard_opinions.py", line 245, in get_fix_list
    data = requests.get(
      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
    ^^^^^^^^^^^^^^^^^
requests.exceptions.ReadTimeout: None: None
```

Reference: https://github.com/freelawproject/courtlistener/actions/runs/6087234508/job/16515358875

**Comment by mlissner** [comment]
Got another crashed test because of this today: https://github.com/freelawproject/courtlistener/actions/runs/6104724213/job/16567160285

**Comment by mlissner** [comment]
Heads up @flooie  and @quevon24
