### ISSUE TITLE
Unable to make dev data: Elastic indexing breaks it

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3306]
I just got this stack trace while trying to run `./manage.py make_dev_data`. Kind of a bummer: 

```
Traceback (most recent call last):
  File "/opt/courtlistener/manage.py", line 15, in <module>
    main()
  File "/opt/courtlistener/manage.py", line 11, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/courtlistener/cl/lib/management/commands/make_dev_data.py", line 119, in handle
    Factory.create_batch(count)
  File "/usr/local/lib/python3.11/site-packages/factory/base.py", line 540, in create_batch
    return [cls.create(**kwargs) for _ in range(size)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/factory/base.py", line 540, in <listcomp>
    return [cls.create(**kwargs) for _ in range(size)]
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/factory/base.py", line 528, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/factory/django.py", line 117, in _generate
    return super()._generate(strategy, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/factory/base.py", line 465, in _generate
    return step.build()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/factory/builder.py", line 271, in build
    postgen_results[declaration_name] = declaration.declaration.evaluate_post(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/factory/declarations.py", line 592, in evaluate_post
    return self.call(instance, step, postgen_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/factory/declarations.py", line 673, in call
    return step.recurse(factory, passed_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/factory/builder.py", line 216, in recurse
    return builder.build(parent_step=self, force_sequence=force_sequence)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/factory/builder.py", line 262, in build
    instance = self.factory_meta.instantiate(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/factory/base.py", line 317, in instantiate
    return self.factory._create(model, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/factory/django.py", line 166, in _create
    return manager.create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/courtlistener/cl/people_db/models.py", line 1062, in save
    super(Position, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 892, in save_base
    post_save.send(
  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/signals_handlers.py", line 65, in wrapper
    return receiver(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/courtlistener/cl/lib/elasticsearch_utils.py", line 57, in wrapper_func
    func(*args, **kwargs)
  File "/opt/courtlistener/cl/lib/es_signal_processor.py", line 718, in handle_save
    ).apply_async()
      ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/canvas.py", line 1034, in apply_async
    return self.apply(args, kwargs, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/canvas.py", line 1272, in apply
    last and (last.get(),), **dict(self.options, **options))
              ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 1024, in get
    raise self.result if isinstance(
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 207, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/_compat.py", line 60, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 202, in _inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py", line 38, in run
    return task._orig_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/courtlistener/cl/search/tasks.py", line 411, in es_save_document
    response = es_document(**es_args, **doc).save(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elasticsearch_dsl/document.py", line 497, in save
    meta = es.index(index=self._get_index(index), **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/client/utils.py", line 347, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/client/__init__.py", line 413, in index
    return self.transport.perform_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/transport.py", line 466, in perform_request
    raise e
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/transport.py", line 427, in perform_request
    status, headers_response, data = connection.perform_request(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/connection/http_urllib3.py", line 291, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/connection/base.py", line 328, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'document_parsing_exception', "[1:1023] failed to parse field [person_child] of type [text] in document with id 'po_2'. Preview of field's value: '{parent=12, name=position}'")
```

**Comment by albertisfu** [comment]
Yeah, the issue here is that the auto-generated index doesn't function correctly with document mappings that utilize the parent-child approach. So, it's necessary to create the index manually using a specific command to ensure it is generated properly. This can also be a problem for developers when creating new Dockets or Persons if the correct index isn't in place.

As a temporary solution, you can delete and recreate the index using the following commands:
For Judges:

`search_index --delete --models people_db.Person`
`search_index --create --models people_db.Person`

For RECAP:
`search_index --delete --models search.Docket`
`search_index --create --models search.Docket`

And the general solution would be to run the `--create` index command when the `cl_django` container is launched, using something like:
`command: ["./manage.py", "search_index --create --models search.Docket"]`

Let me know what you think and if it sounds good I can test and apply this fix.

**Comment by mlissner** [comment]
I ran out of time for dev today, but that makes sense. Whatever solution you think is best will be great. How is it that this hasn't been biting everybody all the time?

**Comment by mlissner** [comment]
Pretty sure this one is fixed too, right?

**Comment by albertisfu** [comment]
Yeah, this is solved! closing.
