### ISSUE TITLE
Celery won't start again

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#675]
I'd get rid of Celery in a heartbeat if there was something to replace it with. Once again on the secondary server, Celery is down and I don't know why. 

When I try to start celery, it says it started, but then nothing is running and we get no log lines:

```
↪ sudo service celeryd start
celery init v10.1.
Using config script: /etc/default/celeryd
celery multi v3.1.19 (Cipater)
> Starting nodes...
	> w2@courtlistener.com: OK
```

God, I've lost too many hours to this daemon. It was one weeks ago that I was in this exact place. I eventually figured it out, but I can't find my notes, or maybe I didn't make any.

**Comment by mlissner** [comment]
I was able to find the error with: 

    sudo C_FAKEFORK=1 bash -x /etc/init.d/celeryd start

Which then reported: 

```txt
celery multi v3.1.19 (Cipater)
> Starting nodes...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/celery/__main__.py", line 54, in <module>
    main()
  File "/var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/bin/celery.py", line 770, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/bin/celery.py", line 762, in handle_argv
    return self.execute(command, argv)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/bin/celery.py", line 694, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 95, in __init__
    self.app.loader.init_worker()
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/loaders/base.py", line 128, in init_worker
    self.import_default_modules()
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/loaders/base.py", line 116, in import_default_modules
    signals.import_modules.send(sender=self.app)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/amqp/utils.py", line 42, in __call__
    self.set_error_state(exc)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/amqp/utils.py", line 39, in __call__
    **dict(self.kwargs, **kwargs) if self.kwargs else kwargs
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/app/base.py", line 330, in _autodiscover_tasks
    self.loader.autodiscover_tasks(packages, related_name)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/loaders/base.py", line 251, in autodiscover_tasks
    related_name) if mod)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/loaders/base.py", line 272, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/loaders/base.py", line 298, in find_related_module
    return importlib.import_module('{0}.{1}'.format(package, related_name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/courtlistener/cl/api/tasks.py", line 12, in <module>
    from cl.api.utils import BulkJsonHistory
  File "/var/www/courtlistener/cl/api/utils.py", line 18, in <module>
    from rest_framework_filters import RelatedFilter
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/rest_framework_filters/__init__.py", line 3, in <module>
    from .filterset import FilterSet
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/rest_framework_filters/filterset.py", line 11, in <module>
    from django_filters import filterset, rest_framework
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django_filters/rest_framework/__init__.py", line 3, in <module>
    from .backends import DjangoFilterBackend
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django_filters/rest_framework/backends.py", line 6, in <module>
    from rest_framework.filters import BaseFilterBackend
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/rest_framework/filters.py", line 43, in <module>
    from django_filters.rest_framework.filterset import FilterSet as DFFilterSet
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django_filters/rest_framework/filterset.py", line 9, in <module>
    from .filters import BooleanFilter, IsoDateTimeFilter
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django_filters/rest_framework/filters.py", line 3, in <module>
    from ..widgets import BooleanWidget
ImportError: cannot import name BooleanWidget
	> w2@courtlistener.com: * Child terminated with errorcode 1
FAILED
```

**Comment by mlissner** [comment]
I've seen this error before, having to do with BooleanWidget, but I forget where, and I forget what the solution was. Grr.

**Comment by mlissner** [comment]
Well, this was weird. Somehow we had two versions of django_filter installed at the same time. I just can't imagine how this could even happen, but here's a cleaned up log of the fix:

```python
↪ cat /var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django_filters/widgets.py
from __future__ import absolute_import
from __future__ import unicode_literals

from itertools import chain
try:
    from urllib.parse import urlencode
except:
    from urllib import urlencode  # noqa

from django import forms
from django.db.models.fields import BLANK_CHOICE_DASH
from django.forms.widgets import flatatt
try:
    from django.utils.encoding import force_text
except:  # pragma: nocover
    from django.utils.encoding import force_unicode as force_text  # noqa
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _


class LinkWidget(forms.Widget):
    def __init__(self, attrs=None, choices=()):
        super(LinkWidget, self).__init__(attrs)

        self.choices = choices

    def value_from_datadict(self, data, files, name):
        value = super(LinkWidget, self).value_from_datadict(data, files, name)
        self.data = data
        return value

    def render(self, name, value, attrs=None, choices=()):
        if not hasattr(self, 'data'):
            self.data = {}
        if value is None:
            value = ''
        final_attrs = self.build_attrs(attrs)
        output = ['<ul%s>' % flatatt(final_attrs)]
        options = self.render_options(choices, [value], name)
        if options:
            output.append(options)
        output.append('</ul>')
        return mark_safe('\n'.join(output))

    def render_options(self, choices, selected_choices, name):
        selected_choices = set(force_text(v) for v in selected_choices)
        output = []
        for option_value, option_label in chain(self.choices, choices):
            if isinstance(option_label, (list, tuple)):
                for option in option_label:
                    output.append(
                        self.render_option(name, selected_choices, *option))
            else:
                output.append(
                    self.render_option(name, selected_choices,
                                       option_value, option_label))
        return '\n'.join(output)

    def render_option(self, name, selected_choices,
                      option_value, option_label):
        option_value = force_text(option_value)
        if option_label == BLANK_CHOICE_DASH[0][1]:
            option_label = _("All")
        data = self.data.copy()
        data[name] = option_value
        selected = data == self.data or option_value in selected_choices
        try:
            url = data.urlencode()
        except AttributeError:
            url = urlencode(data)
        return self.option_string() % {
             'attrs': selected and ' class="selected"' or '',
             'query_string': url,
             'label': force_text(option_label)
        }

    def option_string(self):
        return '<li><a%(attrs)s href="?%(query_string)s">%(label)s</a></li>'


class RangeWidget(forms.MultiWidget):
    def __init__(self, attrs=None):
        widgets = (forms.TextInput(attrs=attrs), forms.TextInput(attrs=attrs))
        super(RangeWidget, self).__init__(widgets, attrs)

    def decompress(self, value):
        if value:
            return [value.start, value.stop]
        return [None, None]

    def format_output(self, rendered_widgets):
        return '-'.join(rendered_widgets)


class LookupTypeWidget(forms.MultiWidget):
    def decompress(self, value):
        if value is None:
            return [None, None]
        return value
```

Note that the Booleanwidget is indeed not in that file. I checked on the new version of CL, and the same file actually had the widget. Very peculiar.

`pip freeze` showed that we had the right version installed, and matched up nicely with `pip freeze` on the working server, so I guess it's uninstall and re-install time.

```
↪ cl && sudo ../.virtualenvs/courtlistener/bin/pip uninstall django_filter
Uninstalling django-filter-0.15.3: <-- This is the correct version according to requirements.txt
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filter-0.15.3.dist-info/DESCRIPTION.rst
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filter-0.15.3.dist-info/LICENSE.txt
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filter-0.15.3.dist-info/METADATA
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filter-0.15.3.dist-info/RECORD
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filter-0.15.3.dist-info/WHEEL
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filter-0.15.3.dist-info/metadata.json
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filter-0.15.3.dist-info/top_level.txt
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/__init__.py
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/__init__.pyc
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/compat.py
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/compat.pyc
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/conf.py
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/conf.pyc
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/exceptions.py
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/exceptions.pyc
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/fields.py
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/fields.pyc
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/filters.py
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/filters.pyc
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/filterset.py
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/filterset.pyc
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/locale/de/LC_MESSAGES/django.mo
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/locale/de/LC_MESSAGES/django.po
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/locale/es_AR/LC_MESSAGES/django.mo
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/locale/es_AR/LC_MESSAGES/django.po
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/locale/fr/LC_MESSAGES/django.mo
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/locale/fr/LC_MESSAGES/django.po
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/locale/pl/LC_MESSAGES/django.mo
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/locale/pl/LC_MESSAGES/django.po
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/locale/zh_CN/LC_MESSAGES/django.po
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/models.py
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/models.pyc
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/rest_framework/__init__.py
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/rest_framework/__init__.pyc
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/rest_framework/backends.py
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/rest_framework/backends.pyc
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/rest_framework/filters.py
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/rest_framework/filters.pyc
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/rest_framework/filterset.py
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/rest_framework/filterset.pyc
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/utils.py
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/utils.pyc
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/views.py
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/views.pyc
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/widgets.py
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filters/widgets.pyc
Proceed (y/n)? y
  Successfully uninstalled django-filter-0.15.3
```

Great. It's uninstalled.

```
↪ cl && sudo ../.virtualenvs/courtlistener/bin/pip install django_filter
Requirement already satisfied: django_filter in /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages
```

### WTF?

```
↪ cl && sudo ../.virtualenvs/courtlistener/bin/pip uninstall django_filter
The directory '/home/mlissner/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling django-filter-0.11.0:
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filter-0.11.0.dist-info/DESCRIPTION.rst
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filter-0.11.0.dist-info/INSTALLER
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filter-0.11.0.dist-info/LICENSE.txt
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filter-0.11.0.dist-info/METADATA
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filter-0.11.0.dist-info/RECORD
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filter-0.11.0.dist-info/WHEEL
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filter-0.11.0.dist-info/metadata.json
  /var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django_filter-0.11.0.dist-info/top_level.txt
Proceed (y/n)? y
  Successfully uninstalled django-filter-0.11.0
```

THAT WAS WEIRD.

```
↪ cl && sudo ../.virtualenvs/courtlistener/bin/pip uninstall django_filter
Cannot uninstall requirement django-filter, not installed
```

Thank goodness.

```
↪ cl && sudo ../.virtualenvs/courtlistener/bin/pip install django_filter==0.15.3
Collecting django_filter==0.15.3
/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading django_filter-0.15.3-py2.py3-none-any.whl (48kB)
    100% |████████████████████████████████| 51kB 3.1MB/s 
Installing collected packages: django-filter
Successfully installed django-filter-0.15.3
```

Good. Testing....

```
↪  cl && sudo -H -u www-data ../.virtualenvs/courtlistener/bin/python ./manage.py shell
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
Type "copyright", "credits" or "license" for more information.

IPython 3.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from django_filters.rest_framework.filters import BooleanWidget

In [2]: exit
```

OK. Let's start celery.

```
↪ sudo service celeryd startcelery init v10.1.
Using config script: /etc/default/celeryd
celery multi v3.1.19 (Cipater)
> Starting nodes...
	> w2@courtlistener.com: OK
```

Yep. Weird and frustrating.

**Comment by mlissner** [comment]
I've got a Q on Stackoverflow. Maybe it'll reveal something?
