### ISSUE TITLE
Transaction deadlocks making party and attorney merging fail

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#814]
I got a funny error message today:

```
Traceback (most recent call last):
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/courtlistener/cl/recap/tasks.py", line 785, in process_recap_docket
    add_parties_and_attorneys(d, data['parties'])
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/var/www/courtlistener/cl/recap/tasks.py", line 666, in add_parties_and_attorneys
    date_terminated=party['date_terminated'])
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/query.py", line 563, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1062, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
OperationalError: deadlock detected
DETAIL:  Process 16816 waits for ShareLock on transaction 302510152; blocked by process 16533.
Process 16533 waits for ShareLock on transaction 302503949; blocked by process 16816.
HINT:  See server log for query details.
```

As I understand it (without delving deeply in), it looks like one query tried to write to these records while another had them in a transaction. Naturally, that fails. What we need to do, I think is just wait a second and try again. 

Since attorney and party merging happens in its own transaction as part of the docket parsing, and since we don't want to redo the entire docket parsing, we put the retry mechanism on only the party and attorney method. This should work fine, but if it fails more times than the retry method allows, we won't get parties and attorneys for the item. That's probably OK too. Next time.

Another way to do this, probably, would be to wrap the entire docket parsing business in a big old transaction, and to wrap the party and attorney stuff in a transaction within that. Then, when attorney and party failed due to a deadlock, we could kill the parent transaction and redo the whole shebang. That's probably better, but it's also complex, and also involves more compute time, especially with larger dockets. So...I'm going to try this, and hopefully it'll do a nice job. If not, we can go bigger next time.

**Comment by mlissner** [comment]
We had some discussion about this on Slack. Here is the error from the logs:

```
2018-03-27 09:52:24 PDT ERROR:  deadlock detected
2018-03-27 09:52:24 PDT DETAIL:  Process 16816 waits for ShareLock on transaction 302510152; blocked by process 16533.
	Process 16533 waits for ShareLock on transaction 302503949; blocked by process 16816.
	Process 16816: UPDATE "people_db_partytype" SET "date_terminated" = NULL, "extra_info" = '' WHERE ("people_db_partytype"."party_id" = 1440668 AND "people_db_partytype"."docket_id" = 4261857 AND "people_db_partytype"."name" = 'Plaintiff')
	Process 16533: DELETE FROM "people_db_partytype" WHERE ("people_db_partytype"."docket_id" = 4261857 AND NOT ("people_db_partytype"."party_id" IN (376832, 405505, 1294349, 1294350, 1294354, 1294355, 404142, 1294361, 1294362, 1294363, 1294367, 1294374, 32812, 405550, 213043, 1292981, 1294400, 8259, 196681, 405584, 405586, 405589, 1294434, 405610, 176245, 213112, 405627, 405629, 405630, 1294467, 1294468, 1294471, 405641, 737419, 405644, 405650, 404846, 405654, 405657, 405530, 1294498, 405668, 405670, 1294507, 524462, 131250, 1294526, 405696, 405700, 405701, 1294538, 405716, 405717, 405721, 405724, 405725, 528612, 405741, 1294584, 37113, 1294588, 405764, 405767, 65806, 1294607, 655636, 405785, 430362, 1294620, 1294623, 405792, 405801, 213298, 405812, 405813, 1294647, 405818, 1278272, 1294657, 213314, 405829, 1294662, 405831, 1294666, 1294667, 405837, 1294676, 1294677, 1294678, 1294679, 1294681, 1293711, 405855, 405860, 405861, 147815, 1294698, 405867, 1294703, 1294704, 408055, 404883, 1294709, 405885, 405231, 385409, 1294723, 
2018-03-27 09:52:24 PDT HINT:  See server log for query details.
```
