### ISSUE TITLE
no chrome binary at /usr/bin/google-chrome error when running tests

### ISSUE THREAD

**Issue by davidxia** [freelawproject/courtlistener#877]
I followed the [instructions to run tests](https://github.com/freelawproject/courtlistener/blob/master/DEVELOPING.md#running-the-test-suite).

After installing chromedriver via `brew cask install chromedriver` and getting through [step 5 here](https://github.com/freelawproject/courtlistener/blob/master/DEVELOPING.md#selenium-tests-when-headless), I ran the command below in my Vagrant VM (created via `vagrant up` from [freelawmachine](https://github.com/freelawproject/freelawmachine)). I ran the command while on the latest master branch from [courtlistener](https://github.com/freelawproject/courtlistener). I expected all tests to pass but got the following error for several tests: `no chrome binary at /usr/bin/google-chrome`.

```
(courtlistener)vagrant@freelawbox64:/var/www/courtlistener$ cd /var/www/courtlistener && ./manage.py test --noinput cl

...

======================================================================
ERROR: test_non_admin_viewing_blocked_audio_page (cl.tests.test_issue412.AudioBlockedFromSearchEnginesTest)
For a blocked Audio pages, a Non-admin should see NO indication.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/courtlistener/cl/tests/base.py", line 69, in setUp
    self.reset_browser()
  File "/var/www/courtlistener/cl/tests/base.py", line 83, in reset_browser
    self.browser = self._create_browser(options)
  File "/var/www/courtlistener/cl/tests/base.py", line 55, in _create_browser
    desired_capabilities=capabilities)
  File "/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: no chrome binary at /usr/bin/google-chrome
  (Driver info: chromedriver=2.42.591059 (a3d9684d10d61aa0c45f6723b327283be1ebaad8),platform=Mac OS X 10.13.6 x86_64)


======================================================================
ERROR: test_admin_viewing_blocked_docket (cl.tests.test_issue412.DocketBlockedFromSearchEnginesTest)
For a blocked Dockets, an Admin should see indication.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/courtlistener/cl/tests/base.py", line 69, in setUp
    self.reset_browser()
  File "/var/www/courtlistener/cl/tests/base.py", line 83, in reset_browser
    self.browser = self._create_browser(options)
  File "/var/www/courtlistener/cl/tests/base.py", line 55, in _create_browser
    desired_capabilities=capabilities)
  File "/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: no chrome binary at /usr/bin/google-chrome
  (Driver info: chromedriver=2.42.591059 (a3d9684d10d61aa0c45f6723b327283be1ebaad8),platform=Mac OS X 10.13.6 x86_64)
```

If I comment out two lines containing `'/usr/bin/google-chrome'` [in base.py](https://github.com/freelawproject/courtlistener/blob/master/cl/tests/base.py), this error goes away (replaced by other errors though).

Is there something I'm doing wrong?

**Comment by mlissner** [comment]
Actually, I think what happened is we switched the driver to Chrome rather than PhantomJS and so now there's a dependency that we don't have. This should probably be filed over in the Vagrant repo. How are your Vagrant skills?
